stages:
  - release

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive


publish:
  image: node:12
  stage: release
  script:
    - apt-get update && apt-get install -y cmake
    - npm install @semantic-release/git
    - npm install @semantic-release/gitlab
    - npx semantic-release@15
  tags:
    - docker